languages:
  - English
  - Mandarin Chinese
  - Hindi
  - Spanish
  - French
  - Arabic
  - Bengali
  - Russian
  - Portuguese
  - Urdu
  - Indonesian
  - German
  - Japanese
  - Marathi
  - Telugu
  - Turkish
  - Tamil
  - Vietnamese
  - Korean
  - Italian
  - Hausa
  - Thai
  - Persian (Farsi)
  - Gujarati
  - Polish
  - Ukrainian
  - Kannada
  - Malayalam
  - Oriya (Odia)
  - Burmese
  - Somali
  - Uzbek
  - Dutch
  - Kurdish
  - Amharic
  - Cebuano
  - Malay
  - Hmong
  - Armenian
  - Serbian
  - Pashto
  - Nepali
  - Sinhala
  - Khmer
  - Lao
  - Hebrew
  - Zulu
  - Shona
  - Xhosa
  - Romanian
  - Tagalog (Filipino)
